### Admin Registration Test
POST http://localhost:5000/api/admin/register
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### Admin Login Test
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### Get All Projects (Public Route)
DELETE http://localhost:5000/api/admin/delete/075492957235987


##create Project
